// Command sheets regenerates every review sheet and writes the index that links them.
//
//	go run ./tools/sheets
//
// It exists because the sheets are committed *(owner's call, 2026-08-23)* and a committed
// artefact has to be regenerable by one command. Four commands remembered in the right order is
// how three of them end up current and one of them ends up lying, and a stale sheet is worse than
// no sheet — it is a picture of a catalogue that no longer exists.
//
// # It shells out rather than importing
//
// Each sheet is its own `package main`, so there is nothing to import: Go has no way for one
// command to call another's `run`. The alternative was a shared library package under tools/ with
// four thin mains over it, and that is a worse trade than it looks — the sheets have almost
// nothing in common but the words `png.Encode`, and a library would exist to be a seam this file
// already is. So this runs `go run ./tools/<name>` and reports what each one said.
//
// **A failing sheet fails the whole run**, and the rest are still attempted first. A tool that
// stopped at the first error would leave the index claiming four sheets and the directory holding
// two.
//
// # The index
//
// `docs/sheets/index.html` is written here rather than by any one sheet, because no sheet knows
// the others exist. It is the page a clone opens.
package main

import (
	"flag"
	"fmt"
	"html/template"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// root is where the sheets are written. It is the default every sheet tool already carries, said
// once more here because this file writes the index that sits above them.
const root = "docs/sheets"

// sheet is one review page: the tool that writes it, and what a reader should open it for.
//
// **The blurb is what the index is for.** A directory listing of four names tells a reader
// nothing about which one answers their question, and the questions are genuinely different —
// one is a drawing-board, three are reports on the real catalogues.
var sheets = []sheet{
	{
		Dir:   "cardsheet",
		Tool:  "./tools/cardsheet",
		Title: "Card sheet",
		Blurb: "Every card variation, plus the backs, the states and the deck rows. " +
			"**A drawing-board rather than a report** — it writes its own contents out, so it can " +
			"show cards the rules cannot deal yet.",
	},
	{
		Dir:   "ringsheet",
		Tool:  "./tools/ringsheet",
		Title: "Ring sheet",
		Blurb: "Every ring, grouped by rarity, with its price, the sentence it prints and the " +
			"rules that actually fire side by side. The only place the authored line and the rule " +
			"can be read against each other.",
	},
	{
		Dir:   "wormsheet",
		Tool:  "./tools/wormsheet",
		Title: "Worm sheet",
		Blurb: "Every worm, grouped by what it changes about a card. Two are offered after a won " +
			"fight, so this is the whole catalogue a run sees a fifth of.",
	},
	{
		Dir:   "handsheet",
		Tool:  "./tools/handsheet",
		Title: "Hand sheet",
		Blurb: "Every rung of the hand ladder drawn as an actual hand of real cards, ordered by " +
			"multiplier across all three axes at once — which is the comparison hands.json's " +
			"axis-by-axis layout hides.",
	},
}

// glyphs is the one review picture that is not generated by this command. It has been committed
// since long before the sheets were, at its own path beside its own tool, and moving it would
// break the image diffs GitHub renders against its history. The index links it where it lives.
var glyphs = link{
	Title: "Glyph sheet",
	Href:  "../../tools/glyphsheet/glyphs.png",
	Blurb: "Every generated glyph by every palette, drawn at the scale a card uses it and again " +
		"enlarged. One committed PNG, so a change to a silhouette shows up in review as a picture.",
}

func main() {
	dir := flag.String("dir", filepath.FromSlash(root),
		"directory to write the sheets and the index into")
	indexOnly := flag.Bool("index", false, "rewrite the index without regenerating the sheets")
	flag.Parse()

	if err := run(*dir, *indexOnly); err != nil {
		log.Fatal(err)
	}
}

func run(dir string, indexOnly bool) error {
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("making %s: %w", dir, err)
	}

	var failed []string
	if !indexOnly {
		for _, s := range sheets {
			fmt.Printf("== %s\n", s.Tool)
			out, err := exec.Command("go", "run", s.Tool, "-dir", filepath.Join(dir, s.Dir)).CombinedOutput()
			os.Stdout.Write(out)
			if err != nil {
				// Reported and carried on: see the package comment. A half-written directory under a
				// complete index is the failure this avoids.
				failed = append(failed, s.Tool)
			}
		}
	}

	out := filepath.Join(dir, "index.html")
	f, err := os.Create(out)
	if err != nil {
		return fmt.Errorf("creating %s: %w", out, err)
	}
	defer f.Close()

	if err := tmpl.Execute(f, index{Sheets: sheets, Glyphs: glyphs}); err != nil {
		return fmt.Errorf("writing %s: %w", out, err)
	}
	fmt.Printf("\nwrote %s\n", out)

	if len(failed) > 0 {
		return fmt.Errorf("these sheets failed and are now stale: %s", strings.Join(failed, ", "))
	}
	return nil
}

type sheet struct {
	Dir   string
	Tool  string
	Title string
	Blurb string
}

// Href is where the index links, which is the sheet's own page rather than its directory: a
// directory link lands on whatever the host decides to serve, and a file:// clone decides on a
// listing.
func (s sheet) Href() string { return s.Dir + "/index.html" }

type link struct {
	Title string
	Href  string
	Blurb string
}

type index struct {
	Sheets []sheet
	Glyphs link
}

// The index page. Deliberately the plainest thing here — it is a list of four links, and every
// pixel of design on it is a pixel not spent on the sheets it points at.
var tmpl = template.Must(template.New("index").Parse(`<!doctype html>
<meta charset="utf-8">
<title>Ascending Duel — review sheets</title>
<style>
  :root { --ground: #e2d0b0; --ink: #2c2822; --dim: #6b6355; --rule: #c4b294; --panel: #ede0c8; }
  * { box-sizing: border-box; }
  body {
    margin: 0; padding: 40px 28px 64px; background: var(--ground); color: var(--ink);
    font: 15px/1.6 -apple-system, "Segoe UI", system-ui, sans-serif;
  }
  .wrap { max-width: 760px; margin: 0 auto; }
  h1 { font-size: 24px; margin: 0 0 6px; font-weight: 600; }
  p.note { color: var(--dim); font-size: 13px; margin: 0 0 6px; }
  a.card {
    display: block; text-decoration: none; color: inherit;
    background: var(--panel); border: 1px solid var(--rule); border-radius: 8px;
    padding: 16px 18px; margin-top: 14px;
  }
  a.card:hover { border-color: var(--ink); }
  a.card .title { font-size: 17px; font-weight: 600; }
  a.card .blurb { color: var(--dim); font-size: 13.5px; margin-top: 4px; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 12.5px; }
</style>

<div class="wrap">
  <h1>Review sheets</h1>
  <p class="note">
    Generated pictures of what the game's catalogues actually hold. They are committed, so this
    page opens from a bare clone with no Go toolchain — but that also means they are only as
    current as the last run of <code>go run ./tools/sheets</code>. Regenerate after changing a
    catalogue, and not otherwise.
  </p>
  <p class="note">
    Every card on every sheet is drawn by <code>internal/cards</code>, the same code the game
    blits, so a sheet cannot show a card the game would draw differently.
  </p>

  {{range .Sheets}}
    <a class="card" href="{{.Href}}">
      <div class="title">{{.Title}}</div>
      <div class="blurb">{{.Blurb}}</div>
    </a>
  {{end}}

  <a class="card" href="{{.Glyphs.Href}}">
    <div class="title">{{.Glyphs.Title}}</div>
    <div class="blurb">{{.Glyphs.Blurb}}</div>
  </a>
</div>
`))
